### ISSUE TITLE
Insert user pass

### ISSUE THREAD

**Issue by eponcehenriquez** [jhonmike/StartApiZend#8]
estimado
muitas saudações, uma menção por mais de olhar que eu não poderia gerir para inserir um novo usuário, ou / auth / registar-se ou admin / user / register. Ao criar nenhum problema, mas quando você faz logon senha não é reconhecido. bd rever como inserir a senha e encontrei este. Senha era "demo2", mas em bd "MQ ==" aparece. você pode me ajudar onde está o erro.

muito obrigado

**Comment by jhonmike** [comment]
esta certo, no banco ele grava a senha criptografada, mais o porque não esta funcionando o seu login eu não sei! aqui esta normal, vou fazer mais alguns testes!

**Comment by JamesAndresCM** [comment]
Hi bro. i've been trying to  install your module, i think that is very helpfull, but i have a problem. When i create an a new user, the password is not recognize :/ , I look in the database but i not find nothing, Please help me.
Regards.

**Comment by jhonmike** [comment]
I decided to reactivate the project, I am starting an upgrade project, soon to post news!

**Comment by eponcehenriquez** [comment]
thank you very much is the best I found on the web ...

**Comment by jhonmike** [comment]
Thank you: D, I'm upgrading to the new modules zf3: D
